### ISSUE TITLE
Recommendation for Viewing on Public IP

### ISSUE THREAD

**Issue by stone212** [carsenk/explorer#11]
What is the recommended way to view this explorer from the public internet?  Reverse proxy?  Manually setting the public IP in the config?

Etc.?

**Comment by stone212** [comment]
Duplicated in https://github.com/carsenk/explorer/issues/2

NOTE: I had no luck with reverse proxy.  I could see the page, but got the error that starts the thread I just posted.

**Comment by stone212** [comment]
Here is the solution:

1. Change "localhost" to your public IP in /app/api.js

2. Reverse proxy BOTH port 8000 and 8545

It was that simple.

**Comment by bmatthewshea** [comment]
I know this is closed but instead of using a public IP (which can occasionally change on my end) wouldn't it be better to base this on a DNS name? Is this possible?
