### ISSUE TITLE
Not Showing Blocks

### ISSUE THREAD

**Issue by stone212** [carsenk/explorer#17]
The explorer is not showing blocks.  The UI is coming up, Parity is running, and I get no errors.  Just a blank UI.

![etherexplorerblank](https://user-images.githubusercontent.com/26020999/31066611-f9d84634-a745-11e7-9c32-f960f26107ca.png)

What is a good way to troubleshoot this problem?  What should I look at?  What should I install?  How can I test this in small pieces?

**Comment by 6hundred** [comment]
are your trying this on localhost or on some VPS. trying on VPS gives same to me. any luck so far.

**Comment by stone212** [comment]
@6hundred 

VPS.  No progress yet.

**Comment by stone212** [comment]
@6hundred Is your RPC port available at the same IP address that you are viewing the web interface at?  I had reverse proxied port 8000 but not port 8545.  When I did that, it solved the problem.  You can see the details in the "Network" tab of your browser's Development Console (or Inspect Element in FF).

**Comment by fabius8** [comment]
I have this trouble too, how can i fix this?

**Comment by ghost** [comment]
@stone212  hey sorry to bother you, may seem like a silly question but i need your help :)

- i run a local node on localhost:8545 with parity rpc, which runs fine, so im keeping my GETH_HOSTNAME as "localhost"
- i run the app on localhost:8000 which seems to load the webpage but it is empty as others have stated.

on a side note: i have experimented with [etherparty/explorer](https://github.com/etherparty/explorer) and i made it work, so i cant understand whats the difference and problem im facing as im keeping the same exact configurations for both apps, and both of them are the same. thanks

**Comment by stone212** [comment]
@panosVeran I'm not a dev on this project and I run on a public server so I don't know if I can help.  But have you tried using 127.0.0.1?  Do you have anything else listening on port 8545?  What does `netstat -tulpn`  show?
