### ISSUE TITLE
Is anyone else having CSS issues as of today?

### ISSUE THREAD

**Issue by stone212** [carsenk/explorer#24]
@carsenk you might want to change the location of bootstrap.min.css to:

https://bootswatch.com/3/flatly/bootstrap.min.css

**Comment by kotuliak** [comment]
Or https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css .

**Comment by stone212** [comment]
@kotuliak Just wondering why you prefer that link?

**Comment by val3ri** [comment]
@stone212 - is that the solution for the difference between the screenshot in the description and in the real life (our cases) ?? Changing the bootstrap link in index.html doesn't helped me.. Why looks so shitty ?
![pic1](https://user-images.githubusercontent.com/11741651/32827878-def5f9e0-c9ed-11e7-97a4-6bcc3bd0ea34.jpg)
![pic2](https://user-images.githubusercontent.com/11741651/32827886-e260e072-c9ed-11e7-94fb-919b400fff7e.jpg)

**Comment by kotuliak** [comment]
Think that's an official way of doing it when using bootswatch, and it's done through cdn

**Comment by metaspartan** [comment]
Updated in latest commit: https://github.com/carsenk/explorer/commit/f4bc04beb07c7e62f75ab86284c80d432bca6671
