### ISSUE TITLE
https://coinmarketcap-nexuist.rhcloud.com/api/eth/ ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by phoax** [carsenk/explorer#27]
The service seems down. Is there an easy way to replace it? (like the css bug [#24](https://github.com/carsenk/explorer/issues/24))

**Comment by metaspartan** [comment]
Updated in the latest commit: https://github.com/carsenk/explorer/commit/f4bc04beb07c7e62f75ab86284c80d432bca6671
