### ISSUE TITLE
Zero returned for blockNumber

### ISSUE THREAD

**Issue by chainhead** [carsenk/explorer#35]
Why would `web3.eth.blockNumber` return a zero? Should `geth` be run for a certain duration before explorer can work? In `scripts/controllers/mainController.js`, the function `updateStats()` fails if `web3.eth.blockNumber` returns 0. I used a work-around such that the `blockNum` used subsequently is always greater than equal to 0 and the `-1` doesn't crash the application.

**Comment by sthnaqvi** [comment]
use this explorer already fixed it . https://github.com/sthnaqvi/explorer

**Comment by chainhead** [comment]
You mean this https://github.com/sthnaqvi/explorer/commit/39eaebef947be90d5e099013e148059b27a7f329?diff=split ? Just curious to know, what is this fix? I am not an Angular developer ...
