### ISSUE TITLE
the explorer locks up alot

### ISSUE THREAD

**Issue by Alaradia** [carsenk/explorer#36]
the webpages locks up and the links don't work randomly. also going from the address back to home tends to freeze up

**Comment by sthnaqvi** [comment]
issue fixed in fork repo https://github.com/sthnaqvi/explorer

**Comment by eknoes** [comment]
@sthnaqvi What do you think about submitting a PR?

**Comment by sthnaqvi** [comment]
@eknoes no sir it's not PR, I am trying to help.
