### ISSUE TITLE
Error: invalid argument 0: hex string without 0x prefix

### ISSUE THREAD

**Issue by theaayushanand** [carsenk/explorer#37]
Hello I have the explorer on a debian cloud and geth is running on 8545. The webapp is loading but the block transactions etc are not loading . I can see the following issues in the browser console .

```
Error: invalid argument 0: hex string without 0x prefix
InvalidResponse@http://my-ip:8000/bower_components/web3/dist/web3.min.js:1:27514
require<[43]</s.prototype.send@http://my-ip:8000/bower_components/web3/dist/web3.min.js:2:20636
require<[35]</a.prototype.send@http://my-ip:8000/bower_components/web3/dist/web3.min.js:2:12677
updateStats@http://my-ip:8000/scripts/controllers/mainController.js:118:37
@http://my-ip:8000/scripts/controllers/mainController.js:10:9
e@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:39:94
Xe/this.$get</</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:80:149
L@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:61:140
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:326
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:54:349
V/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:53:388
d/</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:20:4
$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:132:354
$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:133:47
d/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:19:477
e@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:39:94
d@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:19:398
yc@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:20:179
Zd@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:19:1
@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:292:51
a@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:173:491
c@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:35:124
angular.js:12416:17

```
I have changed GETH_HOSTNAME and APP_HOSTNAME to my ip from localhost . do i need to make additional changes before running it on a cloud ?

Thanks for the help

**Comment by sthnaqvi** [comment]
Change GETH_HOSTNAME to your Ethereum Geth node IP and APP_HOSTNAME should be only localhost or 127.0.0.1

**Comment by yuta-take** [comment]
I have the same issue..

my geth machine is NAT Network VPN on public cloud .

fowrd setting.
wan: 8000 to lan: vm_address:8000
wan: 8545 to lan: vm_address:8545

and  geth command line option is 
" --rpcaddr "0.0.0.0" --rpcport 8545 --rpccorsdomain "*" "

and edit the "start" section on the package.json .
"start": "http-server ./app -a 127.0.0.1 -p 8000 -c-1" to 
"start": "http-server ./app -a 0.0.0.0 -p 8000 -c-1"

I will see the explorer screen by the my laptop on the chrome.

and connect to WAN IP:8545 by the Metamask.


but An error has occurred.

angular.js:12416 Error: invalid argument 0: hex string without 0x prefix
    at Object.InvalidResponse (web3.min.js:1)
    at s.send (web3.min.js:2)
    at a.send (web3.min.js:2)
    at updateStats (mainController.js:118)
    at Object.<anonymous> (mainController.js:10)
    at Object.e [as invoke] (angular.js:4473)
    at Q.instance (angular.js:9093)
    at L (angular.js:8205)
    at g (angular.js:7637)
    at g (angular.js:7641)

**Comment by athlona64** [comment]
same issue

**Comment by sthnaqvi** [comment]
@athlona64 use fork of this explorer https://github.com/sthnaqvi/explorer
