### ISSUE TITLE
Question: Unique Network ID and dev Chain?

### ISSUE THREAD

**Issue by stone212** [carsenk/explorer#4]
I am not able to connect to my RPC and I am trying to determine why.

I have the same problem on the parent project and I have an issue posted there:
https://github.com/etherparty/explorer/issues/26

I am now trying to determine if perhaps the problem is because I am using the dev chain.  I am also using a unique network_id.  

Can explorer work with a dev chain?  And does it need to be told the network id?

**Comment by metaspartan** [comment]
Have you changed the geth_command to include the --dev flag in the app.js? https://github.com/carsenk/explorer/blob/master/app/app.js

If you have then I would assume it probably is a bug, this would be more so a question for web3.js git or the original project.

**Comment by stone212** [comment]
No but unless I'm missing something, the geth_command doesn't actually invoke geth.  (Geth has to be manually invoked.)  It's just there as a tooltip/hint to tell you how to invoke geth if explorer can't connect (via web3, I think?)  

I have since tested on the main chain instead of dev, and I still get the same error message.  I may just not know how to use web3.  (I've never used it before and there isn't much documentation.)

But yes, I have posted to the original project.  Thank you for your reply.

**Comment by stone212** [comment]
Is it possible that I have to install web3 into the explorer project somehow?  I can confirm that it is running on geth and that it is responding to curl commands.

 

S

 

Gesendet: Freitag, 17. März 2017 um 00:50 Uhr
Von: "Carsen Klock" <notifications@github.com>
An: carsenk/explorer <explorer@noreply.github.com>
Cc: "Stone C" <stone.212@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [carsenk/explorer] Question: Unique Network ID and dev Chain? (#4)


Have you changed the geth_command to include the --dev flag in the app.js? https://github.com/carsenk/explorer/blob/master/app/app.js

If you have then I would assume it probably is a bug, this would be more so a question for web3.js git or the original project.

**Comment by stone212** [comment]
The problem here was the UI.  I was getting the error even though the explorer was working.  Apparently explorer at this time only supports graphical browsers, not server-side text browsers like w3m.  (An issue inherited from the parent project.)
