### ISSUE TITLE
Unable to connect to geth RPC using LXC

### ISSUE THREAD

**Issue by http403** [carsenk/explorer#50]
I'm trying out the program in LXC environment but unsuccessful. However, explorer refuse to connect to a locally hosted geth inside the LXC. If I change it to LXC's IP address in `app/app.js`, the web page will hang and Chromium ask me to kill it. How can I make it to connect?

**Comment by http403** [comment]
Here's my command to set up geth
```
geth --networkid 33671 --rpc --rpcaddr 0.0.0.0 -rpcport 8545 --rpcapi "web3,eth" --rpccorsdomain "http://10.174.144.236:8000" console
```

**Comment by AYEE0525** [comment]
HI, you can try this:　[https://github.com/sthnaqvi/explorer](url)
This Project maybe good for you.

**Comment by http403** [comment]
Close as stale
