### ISSUE TITLE
Angular sanitize error

### ISSUE THREAD

**Issue by sambengtson** [carsenk/explorer#54]
Running into some web console errors while starting up a new project.  I'm trying to connect to a private chain but I don't think I'm even getting that far in the process.  I've installed all packages with npm and bower as the README suggests.  Any thoughts here?

![capture](https://user-images.githubusercontent.com/5069583/42946261-12878ad6-8b30-11e8-9abf-cbd9e4075b2f.PNG)

**Comment by VGLoic** [comment]
There is a little mess in the bower.json files with the versions of the angular dependencies and you need to align all of them to a version 1.4.x (or maybe higher but this is what I took).
Everything will be in the app/bower_components:

- In angular/bower.json
`{
  "name": "angular",
  "version": "1.4.11",
  "license": "MIT",
  "main": "./angular.js",
  "ignore": [],
  "dependencies": {
  },
  "resolutions": {
    "angular": "~1.4.x"
  }
}`

- In angular-bootstrap/bower.json and .bower.json modify
`"dependencies": {
    "angular": ">=1.3.0"
  }`
into
`"dependencies": {
        "angular": "~1.4.x"
    }`

- In angular-sanitize/bower.json and .bower.json change all the versions of angular and angular-sanitize 1.5.7 into 1.4.11

I also had a problem with web3 and I changed the version from 0.12.0 to 0.14.0 in app/bower_components/web3/bower.json and .bower.json and in the main bower.json at the root.

**Comment by dukei** [comment]
No, you should not modify anything under app/bower_components. You should modify only `bower.json` and `package.json` at the project root.

To run the explorer do the following:
1. Clone the repository.
1. Modify `package.json`:
    1. Replace the dev dependency for `http-server` with line: `"http-server": "^0.9.0",`
1. Modify `bower.json`:
    1. Add line `    "angular-sanitize": "~1.4.0",` to dependencies.
    1. Replace dependency for `web3` with line: `"web3": "~0.14.0",`
    1. Add `resolutions` section:
```javascript
      "resolutions": {
        "angular": "~1.4.0",
        "angular-sanitize": "~1.4.0"
      }
```

Modified `package.json` and `bower.json` are attached.

After you have made the changes run the explorer with `npm start`.



[explorer.zip](https://github.com/carsenk/explorer/files/2232187/explorer.zip)

**Comment by VGLoic** [comment]
Great! Thanks a lot for this better improvement!

**Comment by sambengtson** [comment]
I'm having trouble with bower for whatever reason.  But I'll create a PR once I confirm this works.  Thanks guys

**Comment by bestplay** [comment]
@dukei 

After follow your solution, i got this:
`web3 is not defined`

And bower got this:
```
invalid-meta for:/tmp/username/bower/d55930f03965659da7442e54ee12f1d8-6982-0Gu829/bower.json
invalid-meta The "main" field cannot contain minified files
invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["./dist/web3.js","./dist/web3.min.js"]

```

**Comment by dukei** [comment]
Remove this line https://github.com/carsenk/explorer/blob/916fb5e772f44e6346c01ee8cb73dc00086384fe/app/app.js#L103

**Comment by bestplay** [comment]
@dukei  great, it works.

But i want Transaction History . Can i reach that using this Explorer? 
Thanks.
