### ISSUE TITLE
Problem at running explorer webapp

### ISSUE THREAD

**Issue by atari83** [carsenk/explorer#63]
Dears,

When I run the explorer and visit the webpage, i receive this error:
Allow Access to Geth and Refresh the Page
geth --rpc --rpcaddr localhost --rpcport 8545 --rpcapi "web3,eth" --rpccorsdomain "http://192.168.1.210:8000"

And I'm certain that i just ran the geth with equal params but still receive the error .. I also tried to change rpcaddr to 192.168.1.210 and also set vhosts to "*" but same result.

WARN [01-27|16:54:18.686] Switch sync mode from fast sync to full sync 
INFO [01-27|16:54:18.703] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=ExtIP(192.168.1.210)
INFO [01-27|16:54:18.703] Mapped network port                      proto=udp extport=30303 intport=30303 interface=ExtIP(192.168.1.210)
INFO [01-27|16:54:18.704] New local node record                    seq=19 id=02d3ea0fa6a862f4 ip=192.168.1.210 udp=30303 tcp=30303
INFO [01-27|16:54:18.707] IPC endpoint opened                      url=/home/user1/etherhome/geth.ipc
INFO [01-27|16:54:18.709] HTTP endpoint opened                     url=http://localhost:8545         cors=http://192.168.1.210:8000 vhosts=localhost

I'm using geth 1.9.7 on centos 7 btw.

Thanks.

**Comment by conr2d** [comment]
Do you have metamask extenstion in your browser? Refer to the next [link](https://ethereum.stackexchange.com/questions/74076/metamask-blocks-web3-requests).

**Comment by Veterangrail** [comment]
> Dears,
> 
> When I run the explorer and visit the webpage, i receive this error: Allow Access to Geth and Refresh the Page geth --rpc --rpcaddr localhost --rpcport 8545 --rpcapi "web3,eth" --rpccorsdomain "http://192.168.1.210:8000"
> 
> And I'm certain that i just ran the geth with equal params but still receive the error .. I also tried to change rpcaddr to 192.168.1.210 and also set vhosts to "*" but same result.
> 
> WARN [01-27|16:54:18.686] Switch sync mode from fast sync to full sync INFO [01-27|16:54:18.703] Mapped network port proto=tcp extport=30303 intport=30303 interface=ExtIP(192.168.1.210) INFO [01-27|16:54:18.703] Mapped network port proto=udp extport=30303 intport=30303 interface=ExtIP(192.168.1.210) INFO [01-27|16:54:18.704] New local node record seq=19 id=02d3ea0fa6a862f4 ip=192.168.1.210 udp=30303 tcp=30303 INFO [01-27|16:54:18.707] IPC endpoint opened url=/home/user1/etherhome/geth.ipc INFO [01-27|16:54:18.709] HTTP endpoint opened url=http://localhost:8545 cors=http://192.168.1.210:8000 vhosts=localhost
> 
> I'm using geth 1.9.7 on centos 7 btw.
> 
> Thanks.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency
