### ISSUE TITLE
Can this be used in a private chain?

### ISSUE THREAD

**Issue by reiven** [carsenk/explorer#7]
Hi!

I want to know if i can run this a block explorer for a private chain.
I'm using parity instead of geth but i guess that should not affect at all.

Thanks

**Comment by reiven** [comment]
Sure it can

**Comment by GregTheGreek** [comment]
@reiven could you provide any instructions on how you did it?
thanks.

**Comment by SteveKeller** [comment]
"npm start"

in the explorer directory

**Comment by reiven** [comment]
sure @GregTheGreek you can take a look at [this gist](https://gist.github.com/reiven/aa175b7eec3c68e1aa49e0f47dd3805d).
The parity version is kinda outdated but it works
