### ISSUE TITLE
coinmarketcap-nexuist.rhcloud.com CORS

### ISSUE THREAD

**Issue by coreyog** [carsenk/explorer#9]
The ethereum value look up used (coinmarketcap-nexuist.rhcloud.com) does not seem to have CORS turned on and produces a lot of errors in the console and a lot of "loading..." in the page. A new API should be used like perhaps CryptoCompare.

**Comment by coreyog** [comment]
Actually that whole site seems to be down. It's not a CORS issue.

**Comment by metaspartan** [comment]
Updated in latest commit: https://github.com/carsenk/explorer/commit/f4bc04beb07c7e62f75ab86284c80d432bca6671
